package com.douyin.mapper;

import com.douyin.pojo.BGM;
import com.douyin.pojo.BGMExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BGMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    long countByExample(BGMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    int deleteByExample(BGMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    int insert(BGM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    int insertSelective(BGM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    List<BGM> selectByExample(BGMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    BGM selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BGM record, @Param("example") BGMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BGM record, @Param("example") BGMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BGM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BGM record);
}