package com.douyin.mapper;

import com.douyin.pojo.UsersLikeVideos;
import com.douyin.pojo.UsersLikeVideosExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UsersLikeVideosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    long countByExample(UsersLikeVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    int deleteByExample(UsersLikeVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    int insert(UsersLikeVideos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    int insertSelective(UsersLikeVideos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    List<UsersLikeVideos> selectByExample(UsersLikeVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    UsersLikeVideos selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UsersLikeVideos record, @Param("example") UsersLikeVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UsersLikeVideos record, @Param("example") UsersLikeVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UsersLikeVideos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UsersLikeVideos record);
}