package com.douyin.vo;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.data.annotation.Id;

import java.io.Serializable;

@ApiModel(value = "用户对象VO",description = "这是用户对象VO")
public class UserVO implements Serializable {

    private long serialID = 1L;

    private String userToken;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(hidden = true)
    @Id
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "用户名",name = "username",example = "douyinuser",required = true)
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "密码",name = "password",example = "123456",required = true)
    @JsonIgnore
    private String password;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.face_image
     *
     * @mbg.generated
     */
    @ApiModelProperty(hidden = true)
    private String faceImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated
     */
    @ApiModelProperty(hidden = true)
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.fans_counts
     *
     * @mbg.generated
     */
    @ApiModelProperty(hidden = true)
    private Integer fansCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.follow_counts
     *
     * @mbg.generated
     */
    @ApiModelProperty(hidden = true)
    private Integer followCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.receive_like_counts
     *
     * @mbg.generated
     */
    @ApiModelProperty(hidden = true)
    private Integer receiveLikeCounts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.face_image
     *
     * @return the value of user.face_image
     *
     * @mbg.generated
     */
    public String getFaceImage() {
        return faceImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.face_image
     *
     * @param faceImage the value for user.face_image
     *
     * @mbg.generated
     */
    public void setFaceImage(String faceImage) {
        this.faceImage = faceImage == null ? null : faceImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.fans_counts
     *
     * @return the value of user.fans_counts
     *
     * @mbg.generated
     */
    public Integer getFansCounts() {
        return fansCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.fans_counts
     *
     * @param fansCounts the value for user.fans_counts
     *
     * @mbg.generated
     */
    public void setFansCounts(Integer fansCounts) {
        this.fansCounts = fansCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.follow_counts
     *
     * @return the value of user.follow_counts
     *
     * @mbg.generated
     */
    public Integer getFollowCounts() {
        return followCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.follow_counts
     *
     * @param followCounts the value for user.follow_counts
     *
     * @mbg.generated
     */
    public void setFollowCounts(Integer followCounts) {
        this.followCounts = followCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.receive_like_counts
     *
     * @return the value of user.receive_like_counts
     *
     * @mbg.generated
     */
    public Integer getReceiveLikeCounts() {
        return receiveLikeCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.receive_like_counts
     *
     * @param receiveLikeCounts the value for user.receive_like_counts
     *
     * @mbg.generated
     */
    public void setReceiveLikeCounts(Integer receiveLikeCounts) {
        this.receiveLikeCounts = receiveLikeCounts;
    }

    public String getUserToken() {
        return userToken;
    }

    public void setUserToken(String userToken) {
        this.userToken = userToken;
    }
}