package com.douyin.mapper;

import com.douyin.pojo.SearchRecords;
import com.douyin.pojo.SearchRecordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SearchRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    long countByExample(SearchRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int deleteByExample(SearchRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int insert(SearchRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int insertSelective(SearchRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    List<SearchRecords> selectByExample(SearchRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    SearchRecords selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SearchRecords record, @Param("example") SearchRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SearchRecords record, @Param("example") SearchRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SearchRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SearchRecords record);
}