package com.douyin.mapper;

import com.douyin.pojo.UsersFans;
import com.douyin.pojo.UsersFansExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersFansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    long countByExample(UsersFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    int deleteByExample(UsersFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    int insert(UsersFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    int insertSelective(UsersFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    List<UsersFans> selectByExample(UsersFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    UsersFans selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UsersFans record, @Param("example") UsersFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UsersFans record, @Param("example") UsersFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UsersFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UsersFans record);
}